version: "3"
services:
  database:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: flaskblueprint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  flaskblueprint-api:
    image: python:3.7
    links:
      - database:database
    depends_on:
      - database
    env_file:
      - .env
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/flaskblueprint
    restart: always
    environment:
      FLASK_ENV: "production"
    command: >
      bash -c "cd /flaskblueprint && 
      pip install -r requirements.txt && 
      ls migrations || flask db init &&
      flask db migrate &&
      flask db upgrade && 
      flask add-user -u admin -p admin &&
      flask run --host 0.0.0.0"

volumes:
  postgres_data:
